name: Remove old artifacts

on:
  push:
    branches:
    - main

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Remove artifacts
        uses: c-hive/gha-remove-artifacts@v1.2.0
        with:
          age: "1 days"
          # Optional inputs
          # skip-tags: true
          skip-recent: 2
