name: Remove old artifacts

on:
  schedule:
    # Every day at 1am
    - cron: "59 23 * * *"

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Remove artifacts
        uses: c-hive/gha-remove-artifacts@v1.2.0
        with:
          age: "2 days"
          # Optional inputs
          # skip-tags: true
          # skip-recent: 5
